### ISSUE TITLE
Error Handling within Twitter API

### ISSUE THREAD

**Issue by chriskang97** [Leundai/twanalyze#16]
#### Description
Currently, nothing happens if a user inputs an ID that currently doesn't exist or is too ambiguous for the Twitter API to recognize. This issue is to deal with failed GET request in the Twitter API and to have a way to notify users that their search was unsuccessful.

#### To Reproduce
Type in an unknown Twitter handler/user and the screen will be stuck on loading. Additionally, the request will constantly be done on the backend until the user refreshes the page or inputs a new search.  

#### Tasks
- [x] Detect if the GET request failed or was unable to be done and return a response back to the front end indicating as such 
- [x] If there were no Tweets returned, return a response back to the front end indicating as such 
- [x] Fix any other error handlings and document them for fixing

**Comment by chriskang97** [comment]
Covered the tasks listed and merged them in a pull request.
