### ISSUE TITLE
Google Fact Check API 

### ISSUE THREAD

**Issue by chriskang97** [Leundai/twanalyze#17]
#### Description
To expand on our current website, having a fact check functionality can help display the emotions the tweet is provoking along with the accuracy of said Tweet. This can help with future data analytics involving a potential correlation between a person's emotions and the likelihood of them stating a factually correct statement.  The API that will be used for this feature will be the Google Fact Check API. 

#### Tasks
- [ ] Verify that the Google Fact Check API can be compatible with the given data structure and input 
- [ ] Connect to the Google Fact Check API and obtain a test response 
- [ ] Incorporate it into Flask as a GET request and verify its functionality via Postman

**Comment by chriskang97** [comment]
Currently, Google Fact Check API seems to be limited in terms of input as it'll check from news articles based on a query rather than an inputted sentence. There could be specific API calls that suits our needs, but due to the limited time, this feature won't be implemented for the final demo.
