### ISSUE TITLE
Twitter API backend requests

### ISSUE THREAD

**Issue by Leundai** [Leundai/twanalyze#2]
#### Description
Set up Twitter API requests that take in the authentication key of the twitter account from the front end. For now, either using our personal Twitter account of alike to test requests from the backend can help. Once we know that works then we can feed it to #3.

This is dependent on #5 and also is relied on by #3.

#### Files
Twitter API: https://developer.twitter.com/en/docs
If there are libraries that already exist which integrate twitter that can be used too instead of just [requests](https://requests.readthedocs.io/en/master/).

#### Tasks
- [x] Get an API Key
- [x] Set up get requests which get the news feed tweets
- [x] Pass it on to #3, so collaborate to know what format the data will be passed

**Comment by chriskang97** [comment]
Successfully achieved the task and documented the data format.
