### ISSUE TITLE
GET Request Tweet Data

### ISSUE THREAD

**Issue by Leundai** [Leundai/twanalyze#4]
#### Description
Create the GET requests that will be relied on by #1. Will likely be sent as a JSON. But make sure to ask #1 what will be needed for the GET request. This also depends on #2 

#### Files
Reference: https://flask.palletsprojects.com/en/1.1.x/

#### Tasks
- [ ] Create the GET requests for sending in the data
- [ ] To test either use the JSON file that #3 has or create your own
- [ ] Use postman to test your GET requests
