### ISSUE TITLE
MongoDB Implementation 🦾

### ISSUE THREAD

**Issue by Leundai** [Leundai/twanalyze#8]
![Woohoo](https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif)

#### Description 🔍 
This is the solution to avoiding multiple GET requests to Twitter. The goal is that when the front end requests for a username with the parameter GET  ```host.com/timeline?username=JohnLinux ``` we can ask the database if it already exists. If so we just send that in. EZ PZ. Otherwise, we will ask the Twitter API and then store it in the database. (This will be a whole other git issue)

What needs to be done here is to create the Database in MongoDB, Models that mimic a similar structure like the [Model Structure](https://www.notion.so/JSON-Structure-9f861fb2687a4424aa8066eee5827dca#569798fd990441dfa6fee554bf22c6d9). Once we have this done we will create a new issue with the currently existing GET sentimental-timeline request to test it out and update it accordingly if an account is not saved in the database.

If you read through the ReadMe in the backend it should tell you that you'll need to create a .env and so on. So if you want to use that as a reference. Also, I have commented everything out in regards to MongoDB so make sure to uncomment that to implement it back.
#### References 📖 
[MongoDB](https://docs.mongoengine.org/guide/index.html)
[Model Structure](https://www.notion.so/JSON-Structure-9f861fb2687a4424aa8066eee5827dca#569798fd990441dfa6fee554bf22c6d9)

#### Tasks ✔️ 
- [x] Create MongoDB account and set up database
- [x] Share account with teammates so that they can access it too. (This will require emails)
- [x] Create User Profile Model (this could just be User) and the ListFields, StringFields, EmbeddedDocuments for tweets, and so on.
- [ ] Notify the team when this is set up so that we can have a GET function set up to test out!
- [ ] Enjoy time with friends or family!
