### ISSUE TITLE
Sentimental Analysis on Individual Tweets 

### ISSUE THREAD

**Issue by chriskang97** [Leundai/twanalyze#9]
#### Description 🔍
Main current feature of our app in which we will do basic sentimental analysis on an individual tweet and return a numeric value that tells us what emotion the tweet is conveying. This will focus on utilizing the Twitter API/Azure Text Analytic services and creating a function that will take take input of a tweet or list of tweets and output a score or multiple scores for each of those tweet. 

#### References 📖
https://developer.twitter.com/en/docs/tutorials/how-to-analyze-the-sentiment-of-your-own-tweets
https://azure.microsoft.com/en-us/services/cognitive-services/text-analytics/

#### Tasks ✔️
- [x] Set up the Text Analytics in Azure
- [x] Successfully call the Sentimental Analysis API 
- [x] Create a function that takes an input Tweet(s) and output the sentimental score(s)

**Comment by chriskang97** [comment]
Successfully done tasks and implemented them into the backend.
